In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [3]:
df.shape

(7043, 21)

In [4]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [5]:
df[df.duplicated()]

Empty DataFrame
Columns: [customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

[0 rows x 21 columns]

In [6]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [7]:
def summary():
    for column in df.columns:
        print(column+": ")
        print("number of unique values:",df[column].nunique())
        print(df[column].unique()[0:50])
        if df[column].nunique()<=3:
            print(df[column].value_counts())
        print('-'*50)

In [8]:
summary()

customerID: 
number of unique values: 7043
['7590-VHVEG' '5575-GNVDE' '3668-QPYBK' '7795-CFOCW' '9237-HQITU'
 '9305-CDSKC' '1452-KIOVK' '6713-OKOMC' '7892-POOKP' '6388-TABGU'
 '9763-GRSKD' '7469-LKBCI' '8091-TTVAX' '0280-XJGEX' '5129-JLPIS'
 '3655-SNQYZ' '8191-XWSZG' '9959-WOFKT' '4190-MFLUW' '4183-MYFRB'
 '8779-QRDMV' '1680-VDCWW' '1066-JKSGK' '3638-WEABW' '6322-HRPFA'
 '6865-JZNKO' '6467-CHFZW' '8665-UTDHZ' '5248-YGIJN' '8773-HHUOZ'
 '3841-NFECX' '4929-XIHVW' '6827-IEAUQ' '7310-EGVHZ' '3413-BMNZE'
 '6234-RAAPL' '6047-YHPVI' '6572-ADKRS' '5380-WJKOV' '8168-UQWWF'
 '8865-TNMNX' '9489-DEDVP' '9867-JCZSP' '4671-VJLCL' '4080-IIARD'
 '3714-NTNFO' '5948-UJZLF' '7760-OYPDY' '7639-LIAYI' '2954-PIBKO']
--------------------------------------------------
gender: 
number of unique values: 2
['Female' 'Male']
Male      3555
Female    3488
Name: gender, dtype: int64
--------------------------------------------------
SeniorCitizen: 
number of unique values: 2
[0 1]
0    5901
1    1142
Name: SeniorCi

In [9]:
df.drop(['customerID', 'gender', 'SeniorCitizen', 'Partner','Dependents'], axis=1, inplace=True)

In [10]:
df.columns

Index(['tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [11]:
df[df['PhoneService']== 'No']['Churn'].value_counts()

No     512
Yes    170
Name: Churn, dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   tenure            7043 non-null   int64  
 1   PhoneService      7043 non-null   object 
 2   MultipleLines     7043 non-null   object 
 3   InternetService   7043 non-null   object 
 4   OnlineSecurity    7043 non-null   object 
 5   OnlineBackup      7043 non-null   object 
 6   DeviceProtection  7043 non-null   object 
 7   TechSupport       7043 non-null   object 
 8   StreamingTV       7043 non-null   object 
 9   StreamingMovies   7043 non-null   object 
 10  Contract          7043 non-null   object 
 11  PaperlessBilling  7043 non-null   object 
 12  PaymentMethod     7043 non-null   object 
 13  MonthlyCharges    7043 non-null   float64
 14  TotalCharges      7043 non-null   object 
 15  Churn             7043 non-null   object 
dtypes: float64(1), int64(1), object(14)
memory

In [13]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [14]:
le = LabelEncoder()
for column in df.columns:
    if df[column].dtype=='object':
        df[column] = le.fit_transform(df[column])

In [15]:
summary()

tenure: 
number of unique values: 73
[ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55]
--------------------------------------------------
PhoneService: 
number of unique values: 2
[0 1]
1    6361
0     682
Name: PhoneService, dtype: int64
--------------------------------------------------
MultipleLines: 
number of unique values: 3
[1 0 2]
0    3390
2    2971
1     682
Name: MultipleLines, dtype: int64
--------------------------------------------------
InternetService: 
number of unique values: 3
[0 1 2]
1    3096
0    2421
2    1526
Name: InternetService, dtype: int64
--------------------------------------------------
OnlineSecurity: 
number of unique values: 3
[0 2 1]
0    3498
2    2019
1    1526
Name: OnlineSecurity, dtype: int64
--------------------------------------------------
OnlineBackup: 
number of unique values: 3
[2 0 1]
0    3088
2    2429
1    1526
Name: OnlineBackup, dt

In [16]:
x=df.drop('Churn', axis=1)
y=df['Churn']

In [17]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.15, random_state=42)

In [18]:
xtrain.shape

(5986, 15)

In [19]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=17)
knn.fit(xtrain, ytrain)
ypred = knn.predict(xtest)

In [20]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(ytest, ypred))

Accuracy: 0.771050141911069
